### PR TITLE
Added Pnp bipolar transistor

### LINKED ISSUE #40: Create symbol for pnp_bipolar_transistor

### PR DESCRIPTION
**Pull request by mrudulpatil18**
Fixes #40 

updates:

- remade svg for pnp_bipolar_transistor, previous svg had orientation and symmetry issues
- generated and finalized ts files for pnp bipolar transistor
- fixed incorrect names in svg object

image

cc: @seveibar

### CODE REVIEW

**Comment by imrishabh18** [comment]
@mrudulpatil18 I can see that you have added `npn_bipolar` svg as well. Can you please remove that from the PR?

**Comment by mrudulpatil18** [comment]
> @mrudulpatil18 I can see that you have added `npn_bipolar` svg as well. Can you please remove that from the PR?

@imrishabh18 
i have just made a minor change in the svg file of npn bipolar, name of the object in the earlier svg was 'photo_diode'. I fixed that , shall i still remove from this PR ?

**Comment by imrishabh18** [comment]
Ohh okay, never mind looks great. Resolve the merge conflicts and we are good

**Comment by imrishabh18** [comment]
Thanks!

**Pull request merged**
