### PR TITLE
led is now have up right left and down instead of horz and vert

### PR DESCRIPTION
**Pull request by anas-sarkez**
/claim #193

### CODE REVIEW

**Review by seveibar — CHANGES_REQUESTED** [review]
the LED needs slight customization, the arrows indicating the light that is emitted always need to point up.

**Comment by seveibar** [comment]
@anas-sarkez you can modify the result of `rotateSymbol` to flip the arrows i think

**Comment by anas-sarkez** [comment]
/claim #196
Screenshot 2024-11-13 at 8 03 20 PM
@seveibar

**Review by seveibar — APPROVED** [review]

**Comment by anas-sarkez** [comment]
@seveibar should I merge?
and create another pr for flipSymbolOverYAxis and flipSymbolOverXAxis?

**Comment by seveibar** [comment]
@anas-sarkez sure

**Pull request merged**
