### PR TITLE
added grnd symbol

### PR DESCRIPTION
**Pull request by TSP06**
added ground symbol

Screenshot 2024-10-22 071710

### CODE REVIEW

**Review by seveibar — CHANGES_REQUESTED** [review]
A ground symbol only has one pin. Also this symbol looks off, it's really narrow, please make wider!

**Comment by seveibar** [comment]
A ground symbol typically has 3 crossing lines, not sure if you have 3

**Comment by TSP06** [comment]
I connected the second port to the third line in some cases that symbol is used but I'll edit this

**Comment by imrishabh18** [comment]
Closing this as @TSP06 has fixed this in another PR

**Pull request closed without merging**
