### PR TITLE
add svg and ts for silicon_controlled_rectifier

### LINKED ISSUE #52: Create symbol for silicon_controlled_rectifier

### PR DESCRIPTION
**Pull request by bbland1**
fixes #52 

Screenshot 2024-10-03 at 12 13 39 AM

### CODE REVIEW

**Comment by imrishabh18** [comment]
Looks good @bbland1! Can you remove the `package-lock.json` from the PR please?

**Review by imrishabh18 — APPROVED** [review]

**Comment by imrishabh18** [comment]
Also, this green dot should be in the centre cause we will be taking that as the origin when importing to other projects. Sorry, I missed to point it out in the above comment.

**Comment by bbland1** [comment]
@imrishabh18 I'm not sure how to center the green dot on the symbol. I have tried adjusting it with the center values in the json and center it better in Inkscape. It doesn't seem to move from what I have tried.

**Comment by imrishabh18** [comment]
Just checked, the green diamond is generated by the script to get the centre point of the svg. I think this looks cool. Merging it.

Thanks for the contribution! 🚀

**Pull request merged**
