### PR TITLE
illuminated_push_button_open

### PR DESCRIPTION
**Pull request by aman1376**
ref: #29

### CODE REVIEW

**Review by imrishabh18 — APPROVED** [review]
LGTM!!

**Review by seveibar — COMMENTED** [review]
Where did you find this symbol? Id imagine a cross between a button and led for this (eg a push button with arrows coming out)

**Comment by aman1376** [comment]
Screenshot 2024-10-27 at 2 26 28 AM

**Review by seveibar — APPROVED** [review]

**Comment by seveibar** [comment]
ok makes sense!

**Comment by aman1376** [comment]
please merge and close

**Pull request merged**
