### PR TITLE
add SVG snapshot validation script and pre-commit hook

### LINKED ISSUE #213: Error if someone forgets to generate the snapshot for a new symbol
/bounty $12

### PR DESCRIPTION
**Pull request by Anshgrover23**
Fixes #213 
/claim #213

### Screenshots:
Screenshot from 2024-12-06 21-40-04

### CODE REVIEW

**Review by seveibar — APPROVED** [review]
Cc @imrishabh18 for final approval (i personally dont like husky)

**Comment by seveibar** [comment]
also @Anshgrover23 jsyk: This PR isn't a "chore", a "chore" is something that usually could be automated like updating a dependency

**Comment by Anshgrover23** [comment]
@seveibar ok sir.

**Comment by imrishabh18** [comment]
LGTM!

**Review by imrishabh18 — APPROVED** [review]

**Pull request merged**
