### PR TITLE
filled diode #119

### LINKED ISSUE #119: Create symbol for pn_junction_diode

### PR DESCRIPTION
**Pull request by 0SlowPoke0**
fixes #119

### CODE REVIEW

**Comment by imrishabh18** [comment]
Can you run the tests to generate snapshots please? Also, the format  is failing. Please take a look at that

**Review by seveibar — CHANGES_REQUESTED** [review]
basically every diode is a pn junction diode, you can rename this to `filled_diode` and it's acceptable since we don't have a filled diode

**Comment by 0SlowPoke0** [comment]
made the changes

**Comment by 0SlowPoke0** [comment]
sorry to trouble you again i renamed the files are there any other changes that i need to make?

**Comment by imrishabh18** [comment]
@0SlowPoke0 Can you resolve the conflict please? Other than that I think this is good to merge

**Review by seveibar — APPROVED** [review]

**Pull request merged**
