### PR TITLE
feat: add laser diode symbol

### PR DESCRIPTION
**Pull request by Complexlity**
Adds #59 

final_laser_diode

### CODE REVIEW

**Comment by seveibar** [comment]
Hmm is this identical to led? (Light emitting diode?)

**Comment by seveibar** [comment]
image

**Comment by Complexlity** [comment]
> Hmm is this identical to led? (Light emitting diode?)

Yh looks similar but the arrow goes in the other direction 

image

Used the middle one. The ones with the circles is preferred? I can update

**Review by seveibar — CHANGES_REQUESTED** [review]
requesting line 🐸

**Comment by Complexlity** [comment]
> requesting line 🐸

In line with the request. Here's how it looks now
final_laser_diode

**Review by Timer00 — APPROVED** [review]
Looks great!

**Comment by Timer00** [comment]
@Complexlity could you run ``bun test``

**Comment by Complexlity** [comment]
> @Complexlity could you run `bun test`

Done and it's failing with this: 
test_fail

I confirm the test has nothing to do with the updates and is also failing on the main branch

**Comment by Complexlity** [comment]
> @Complexlity could you run `bun test`

I see laser_diode has been added 3 days ago so I'm closing this

Ref: https://github.com/tscircuit/schematic-symbols/blob/main/assets/symbols/laser_diode.svg

**Pull request closed without merging**
