### PR TITLE
fix symbols

### LINKED ISSUE #205: Fix 90%+ of the Symbols Issues
https://github.com/user-attachments/assets/af8f3707-64fa-4afe-94b0-f3b2dfc0f28d

/bounty $60

### PR DESCRIPTION
**Pull request by hunxjunedo**
fixes #205
/claim #205
related to #207

please confirm if all the symbols are okay so i can do the cleanup

### CODE REVIEW

**Review by imrishabh18 — COMMENTED** [review]
Looks great! I think only the arrows are a bit weird in this. Otherwise, looks super 😄

Screenshot 2024-11-20 at 18 31 03

**Comment by hunxjunedo** [comment]
Yeah that's the only one wrong, idk why it's doing that.

**Comment by hunxjunedo** [comment]
So are the symbols ok ? Should i move towards passing the tests ?

**Comment by hunxjunedo** [comment]
@imrishabh18 are the icons good to go ? So I can cleanup things.

**Comment by imrishabh18** [comment]
Yes, you can start cleaning up things. Probably at the end take a look at the arrow of the symbol, we can fix it or not. If not we can merge the other symbols, and create a separate issue to fix that.

**Comment by hunxjunedo** [comment]
looks like the `modify-symbol` has been moved ?

**Comment by hunxjunedo** [comment]
@imrishabh18 this PR is ready to be merged, unfortunately, the arrows couldn't be fixed, perhaps its an issue with the scriptts converting SVG to json.

**Review by seveibar — APPROVED** [review]

**Pull request merged**
