### PR TITLE
Added ground symbol

### PR DESCRIPTION
**Pull request by TSP06**
Issue #171

### CODE REVIEW

**Comment by TSP06** [comment]
issue #171

**Comment by TSP06** [comment]
Hey @seveibar @Timer00 @imrishabh18 please review this

**Review by imrishabh18 — CHANGES_REQUESTED** [review]
Can you remove these 2 files from the PR pls? These are not needed. Otherwise, looks good

**Comment by TSP06** [comment]
@imrishabh18 Done

**Comment by imrishabh18** [comment]
The lock file and the diff png file is still there.

**Comment by TSP06** [comment]
@imrishabh18 i have deleted the two files

**Comment by imrishabh18** [comment]
Looks great! Resolving the merge conflicts will be good to merge

**Comment by TSP06** [comment]
how to resolve conflict @imrishabh18

**Comment by imrishabh18** [comment]
rebase your branch with the `main` branch

**Comment by TSP06** [comment]
@imrishabh18 Done

**Pull request merged**
