### PR TITLE
Introduce dc_ammeter

### LINKED ISSUE #64: Create symbol for dc_ammeter

### PR DESCRIPTION
**Pull request by Timer00**
Fixes #64

### CODE REVIEW

**Review by seveibar — APPROVED** [review]
Looks amazing! Good luck with the conflicts 😬 i was worried about these

**Comment by Timer00** [comment]
> Looks amazing! Good luck with the conflicts 😬 i was worried about these

It was just a simple one from generated/base-symbol-names.ts :)

I marked as [wip] since I have 2 questions:
- I noticed a small blue dot on the ‘A’—I’m guessing it shouldn’t be there? Any ideas on how I can remove it? 
image

- I used type guards to help with TS, but I’m not sure if that’s the preferred approach for this project. If they are, it might make sense to export them. Do you have a suggestion for where they should go?”

**Review by seveibar — APPROVED** [review]

**Comment by seveibar** [comment]
Yea for the A i might draw it with a path rather than use text, the blue square is the alignment and hinestly it might not look right because of how inconsistent font render is somethings, a path would be more reliable

**Comment by seveibar** [comment]
The type guards are fine btw, this project is super lax

**Comment by seveibar** [comment]
But tbc this is good to merge imo, thanks again!!!

**Comment by Timer00** [comment]
> Yea for the A i might draw it with a path rather than use text, the blue square is the alignment and hinestly it might not look right because of how inconsistent font render is somethings, a path would be more reliable

I tried to convert the text to a path using inkscape in a few different ways, but every time it'd end up distorted in the Grid render. The alternative would be to draw the letters myself, but I thought that would end up looking inconsistent with other letters we may add. What would you suggest?

**Comment by imrishabh18** [comment]
Thanks! @Timer00

**Pull request merged**
