### PR TITLE
add workflow for snapshots validation

### LINKED ISSUE #213: Error if someone forgets to generate the snapshot for a new symbol
/bounty $12

### PR DESCRIPTION
**Pull request by Anshgrover23**
fixes #213

### CODE REVIEW

**Review by seveibar — APPROVED** [review]
cool

**Review by imrishabh18 — COMMENTED** [review]
What is the point for this workflow, when we are already checking it before committing?

cc: @seveibar

**Comment by Anshgrover23** [comment]
@imrishabh18 😂😂😂

**Comment by Anshgrover23** [comment]
image

**Pull request merged**
