### PR TITLE
introduce ohm_meter

### LINKED ISSUE #115: Create symbol for ohm_meter

### PR DESCRIPTION
**Pull request by bhavyajain511**
fixes #115

### CODE REVIEW

**Comment by imrishabh18** [comment]
Looks good! But do we need a third text apart from the `{REF}` and `{VAL}` for the Ohm sign?

**Comment by imrishabh18** [comment]
And in vertical, the Ohm sign looks a bit off

**Comment by bhavyajain511** [comment]
I have converted the "Ohm" text into a path to fix the issue. Please review it @imrishabh18

**Comment by imrishabh18** [comment]
@bhavyajain511  Can you use please use the bezier curve in svg? to smooth this. Like how smooth the circle is, the Ohm symbol is literally an arc of that. I think it will be possible

Screenshot 2024-10-05 at 1 51 04 AM

**Comment by seveibar** [comment]
@imrishabh18 i suspect we don't have support for bezier curves although I could be wrong. I think we'd have to implement that first (again could be wrong)

**Comment by imrishabh18** [comment]
@seveibar I added the support for the quadratic bezier curve I think yesterday, when @Timer00 was having trouble adding the text.

https://github.com/tscircuit/schematic-symbols/pull/106

**Comment by seveibar** [comment]
@imrishabh18 nice! good to know

**Comment by Timer00** [comment]
I am currently working on adding better support for text to path conversions. But for this it may be enough to close the path as Sev suggested.

**Comment by bhavyajain511** [comment]
> @bhavyajain511 Can you use please use the bezier curve in svg? to smooth this. Like how smooth the circle is, the Ohm symbol is literally an arc of that. I think it will be possible
> 
> Screenshot 2024-10-05 at 1 51 04 AM

I used bezier curve to create the following ohm symbol:
Screenshot 2024-10-05 at 7 11 08 PM

But on running "bun run generate", following error is shown:
Screenshot 2024-10-05 at 5 56 44 PM

**Comment by imrishabh18** [comment]
Taking a look @bhavyajain511

**Comment by imrishabh18** [comment]
@bhavyajain511 Pull the latest main and rebase your branch with it. I have pushed the update to support the Cubic bezier curve. Let me know if this fixes it

**Comment by bhavyajain511** [comment]
@imrishabh18 error is resolved but the ohm symbol is not displayed properly. Can you help me fix this?

Screenshot 2024-10-05 at 8 47 09 PM

**Comment by imrishabh18** [comment]
Okay, I will take a look

**Review by seveibar — APPROVED** [review]

**Pull request closed without merging**
