### PR TITLE
Introduce dc_voltmeter

### LINKED ISSUE #63: Create symbol for dc_voltmeter

### PR DESCRIPTION
**Pull request by Timer00**
Fixes #63

### CODE REVIEW

**Review by seveibar — APPROVED** [review]
image

**Comment by seveibar** [comment]
GREAT WORK!!!!!!

**Comment by seveibar** [comment]
@Timer00 it looks like you might need to run `bun format` T-T we should add that to the readme!

**Comment by imrishabh18** [comment]
Thanks! @Timer00

**Pull request merged**
