### PR TITLE
added rectifier diode

### PR DESCRIPTION
**Pull request by mrudulpatil18**
Issue: #122 

Screenshot:
image

Reference: https://guidepartantepast.z21.web.core.windows.net/rectifier-diode-circuit-symbol.html

### CODE REVIEW

**Review by Timer00 — APPROVED** [review]
Perfect!

**Review by seveibar — CHANGES_REQUESTED** [review]
it should be "rectifier diodes" (plural) and have 4 diodes. Rectifier diode AFAIK isn't a thing and doesn't turn up on google :/

A rectifier diode circuit typically has 4 diodes

**Comment by seveibar** [comment]
It's more like this:

image

**Comment by mrudulpatil18** [comment]
> it should be "rectifier diodes" (plural) and have 4 diodes. Rectifier diode AFAIK isn't a thing and doesn't turn up on google :/
> 
> A rectifier diode circuit typically has 4 diodes

thanks for the clarification, i was confused regarding that too, and this is the only reference i had found
https://guidepartantepast.z21.web.core.windows.net/rectifier-diode-circuit-symbol.html

i'll start working on the "rectifier diodes"

**Comment by mrudulpatil18** [comment]
@seveibar
made the changes mentioned 

> It's more like this:
> 
> image



Updated Screenshot: 
image

Issue: #122

**Comment by mrudulpatil18** [comment]
Quick questions about this PR:

1.  Should we add 'rectifier_diodes' as a separate symbol like I did here, or scrap it since it’s just a combination of diodes?
2. If we’re keeping it, I accidentally messed up when resolving conflicts. Should I fix it with a new commit, or would it be better to close this PR and start fresh?

**Comment by seveibar** [comment]
@mrudulpatil18 sorry for the delay, the pr looks good, merging!

**Pull request merged**
