### PR TITLE
Refactor rotateAnchor function to handle all orientations

### PR DESCRIPTION
**Pull request by anas-sarkez**

### CODE REVIEW

**Comment by seveibar** [comment]
@anas-sarkez can you update the snapshots?

**Comment by anas-sarkez** [comment]
> @anas-sarkez can you update the snapshots?

I need to create up down left and right  files to give us updates

**Comment by anas-sarkez** [comment]
@seveibar 

Screenshot 2024-11-12 at 8 02 52 AM

**Review by seveibar — APPROVED** [review]
Im confused, shouldnt you run the script to regenerate snap.svg files?

**Comment by anas-sarkez** [comment]
Screenshot 2024-11-12 at 8 16 43 AM
Screenshot 2024-11-12 at 8 16 46 AM
this is diode symbols after refactor rotateAnchor it will update automatically without run `bun generate `

**Pull request merged**
